### ISSUE TITLE
Credentials visible / Kimlik bilgileri görünür

### ISSUE THREAD

**Issue by JesseAye** [oguzhanKomcu/CSharp_OOP_Fundamentals#1]
You have visible login credentials in your code.

Kodunuzda görünür oturum açma bilgileriniz var

**Comment by oguzhanKomcu** [comment]
I couldn't find where it is. Can you show me?

**Comment by JesseAye** [comment]
Please see Pull Request #2

**Comment by JesseAye** [comment]
Issue resolved. Thank you!

**Comment by oguzhanKomcu** [comment]
Thank you very much. I did this to try it here, but forgot to delete it.
Actually, I was going to show you how to use it in another topic. I'm glad
you saw it and let me know. :D

Jesse Ayala ***@***.***>, 17 Şub 2022 Per, 01:55 tarihinde
şunu yazdı:
